### ISSUE TITLE
Question: How to get orb.Geometry of a relation from .pbf file?

### ISSUE THREAD

**Issue by meyermarcel** [paulmach/osm#20]
This is just a question and not an issue.

I understand how OSM data is structured. I use the scanner to extract relations, ways and nodes:

```go
func main() {
	r, err := os.Open("/tmp/myarea.osm.pbf")
	if err != nil {
		panic(err)
	}
	background := context.Background()
	scanner := osmpbf.New(background, r, 0)
	for scanner.Scan() {
		o := scanner.Object()
		switch o.(type) {
		case *osm.Relation:
			// relation
		case *osm.Way:
			// way
		case *osm.Node:
			// node
		}
	}
}
```
I thought using maps to store IDs and so on. But I had the feeling that someone already wrote a solution for this.
Are there any best practices, paths or library APIs to get an `orb.Geometry`-struct of a relation read from a .pbf file?

**Comment by paulmach** [comment]
I don't know of any direct solution to this. I guess exactly how you do it depends on the use case.

Recently I've been looking at https://github.com/pelias/pbf2json which I think will output the connect relation. It uses [leveldb](github.com/syndtr/goleveldb/leveldb) to store the node locations and then the way nodes. 

You could also do 3 passes over the file, find relation, find ways, find nodes.

**Comment by meyermarcel** [comment]
Thanks a lot for your response. This was really helpful for finding the path for a solution.
