### ISSUE TITLE
How to handle dense nodes?

### ISSUE THREAD

**Issue by dmholtz** [paulmach/osm#31]
Decoding OSM PBF files, which contain 'dense nodes' fails:

```
panic: dense node does not include all required fields

goroutine 1 [running]:
main.main()
        /Users/[user]/repos/[repo]/cmd/importer/main.go:76 +0x468
exit status 2
```

The error occurs within the [example code](https://github.com/paulmach/osm/blob/master/osmpbf/README.md) provided in the [README.md](https://github.com/paulmach/osm/blob/master/osmpbf/README.md) of the [osmpbf package](https://github.com/paulmach/osm/tree/master/osmpbf).

The error does not occur with OSM PBF file, which do not contain 'dense nodes' like `Antarctica` from [Geofabrik](https://download.geofabrik.de/index.html)

Is this a bug or have I missed anything?

After some research, it seems to me that [another library](https://github.com/qedus/osmpbf) just ignores the missing fields and the decoding suceeds. Thus, the issue seems to be closely related to my OSM PBF file (which I can unfortunately not share due to its size). It would be interesting to hear if your implementation supports a less strict mode, which also just ignores these fields.

**Comment by paulmach** [comment]
please see https://github.com/paulmach/osm/pull/32 and let me know if it works on your file. It will not error anymore if stuff like timestamp, username, version, etc. is missing.

**Comment by paulmach** [comment]
I downloaded some geofabrik files without PII and it still had these fields. But I made the change for the parsing to be less strict.

I believe this is fixed by https://github.com/paulmach/osm/pull/32

**Comment by dmholtz** [comment]
@paulmach Thank you very much for your response. 

Briefly speaking, #32 does unfortunately not fix the issue but transfers it into your protoscan module, which throws an runtime error due to the nil pointers. In #32 I've given a more detailed error description.
