### ISSUE TITLE
Tags.Find() should return nil not ""

### ISSUE THREAD

**Issue by morandd** [paulmach/osm#42]
OSM nodes can contain tags which specify only a key but no value. For example "building=" is common. Tags.Find() should return [nil] if no key is found, since returning "" could mean that either the tag is missing or that it is present but empty. It is common to want to catch even empty tags.

**Comment by paulmach** [comment]
Changing `func (ts Tags) Find(k string) string` to `func (ts Tags) Find(k string) *string` or `func (ts Tags) Find(k string) (string, bool)` would change the type signature and be more annoying to work with.

Maybe we can add a `func (ts Tags) FindTag(k string) *Tag` to fill that use case.

**Comment by morandd** [comment]
yes, or a HasTag(string) bool function

**Comment by paulmach** [comment]
Create https://github.com/paulmach/osm/pull/45 to add Tags.FindTag and Tags.HasTag methods

**Comment by paulmach** [comment]
Merged and published [v0.7.1](https://github.com/paulmach/osm/releases/tag/v0.7.1)

Thank you for reporting this issue.
