### ISSUE TITLE
pkg-config: exec: "pkg-config": executable file not found in $PATH. on M1 mac

### ISSUE THREAD

**Issue by morandd** [paulmach/osm#43]
this package has a dependency (either directly, or somewhere upstream; I didn't investigate in detail) that will lead to this error on a clean Go lang install on M1 mac:
```   # pkg-config --cflags  -- zlib```

The recommended solution seems to be to use homebrew to install the pkg-config utility
```   brew install pkg-config```

I'm leaving this issue in case it helps future Mac users. 
Perhaps add an entry to the README:

```
##INSTALLATION - Apple Silicon Notes
This package require the "pkg-config" utility which must be installed on Mac using Homebrew. Install Homebrew then install the "pkg-config" package using this comnand:
  brew install pkg-config
```

**Comment by paulmach** [comment]
I made some readme changes for this here https://github.com/paulmach/osm/pull/47

**Comment by paulmach** [comment]
added some notes in https://github.com/paulmach/osm/pull/47 thank you for reporting thi.s
