### ISSUE TITLE
Problem in unmarshalling the json file

### ISSUE THREAD

**Issue by etefaghian** [paulmach/osm#51]
Hello, I have a problem in unmarshalling one of the files that I previously entered in the form of xml in my program.
When I try to unmarshal an element that has tag:type for example :
       "id": 13190773,
        "tags": {
          "type": "route",
        }
I countered this error : unknown type of 'route'
Apparently there is a problem in recognizing types
Thanks in advance

**Comment by paulmach** [comment]
fixed in https://github.com/paulmach/osm/pull/53
