### ISSUE TITLE
Expose the <bounds> element in osmxml

### ISSUE THREAD

**Issue by WillSewell** [paulmach/osm#6]
OSM XML files have a `<bounds>` as one of the first elements. This is not currently exposed by the `osmxml.Scanner`. I think there are two ways of doing this:

1. `Object` returns an `interface{}` instead of `osm.Object`, so it can return `*osm.Bounds`
2. Add a new `Bounds` method, a bit like `osmpbf.Scanner.Header`. This might be nicer from an API point of view, but introduces significantly more complexity. E.g. the `osmxml.Scanner` now needs two states: the state when it is scanning for the `<bounds>` and the state where it is doing regular scanning with `Scan`. This is tricky to get right because it's not well-defined where in the document the `<bounds>` element should be. We could define it as "before an element recognised by the `Scan` method. But this would require some lookahead (in case the <bounds> element doesn't exist. (an option is to  _require_ all documents to contain a `<bounds>` element at a particular location).

@paulmach have you thought about this at all?

For reference, an example OSM XML file with `<bounds>`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API 0.7.55.7 8b86ff77">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base="2019-09-12T17:16:02Z"/>

  <bounds minlat="51.4072000" minlon="-0.2907000" maxlat="51.5913000" maxlon="0.1659000"/>

  <node id="1" lat="51.4779481" lon="-0.0014863" version="20" timestamp="2018-10-31T10:20:19Z" changeset="64040630" uid="1778799" user="SomeoneElse_Revert"/>
  <node id="78112" lat="51.5269760" lon="-0.1457924" version="3" timestamp="2018-10-15T14:49:44Z" changeset="63545352" uid="486343" user="peregrination"/>
...
```

**Comment by paulmach** [comment]
Another option is to just make `osm.Bounds` and `osm.Object` by adding a `TypeObject` and ObjectID functino that return "bounds/0" or something.

I haven't thought about this for a while so I may be missing something but that goes better with what I was trying to do with `osm.Object`.  At first I just had `Feature` and `Element` then I needed to parse users and realized my abstraction wasn't complete so I created object to contain them. Seems like added Bounds to Object makes sense.

What do you think about that solution?

**Comment by WillSewell** [comment]
That would certainly be a lot simpler to implement, although it feels a bit hacky having `osm.Bounds` implement `osm.Object` even though it doesn't have an id. For that reason I think just returning an `interface{}` is better, but I don't feel too strongly one way of the other.

What do you prefer? I'm happy to open a PR.
