### ISSUE TITLE
Can't extract Lat and Lon from WayNodes

### ISSUE THREAD

**Issue by evanoberholster** [paulmach/osm#7]
I am trying to get the polygon coordinates from Osm Ways and Relations. Both seem to have the same behavior. Below I have posted my code. Is there anything that I am doing wrong or why would it not output the Lat and Lon?

Thanks

```Golang
func main() {
	f, err := os.Open("latest.osm.pbf")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	nodeChan := make(chan *osm.Node)
	go nodes(nodeChan)

	wayChan := make(chan *osm.Way)
	go ways(wayChan)

	relationChan := make(chan *osm.Relation)
	go relations(relationChan)

	scanner := osmpbf.New(context.Background(), f, 3)
	defer scanner.Close()

	for scanner.Scan() {
		switch e := scanner.Object().(type) {
		case *osm.Node:
			//fmt.Println(e.Point())
			//nodeChan <- e
			//fmt.Println(e.TagMap())
		case *osm.Way:
			//wayChan <- e
			fmt.Println(e.Nodes.Bound())
			//fmt.Println("way")
		case *osm.Relation:
			//relationChan <- e
			//fmt.Println("relation")
		}
	}

	scanErr := scanner.Err()
	if scanErr != nil {
		panic(scanErr)
	}
}
```

This returns... 
```
{[0 0] [0 0]}
{[0 0] [0 0]}
{[0 0] [0 0]}
{[0 0] [0 0]}
{[0 0] [0 0]}
{[0 0] [0 0]}
{[0 0] [0 0]}
{[0 0] [0 0]}
{[0 0] [0 0]}
{[0 0] [0 0]}
```

**Comment by paulmach** [comment]
unfortunately that's not how the latest.osm.pbf file is structured. There are nodes with lng/lat, etc.  And then the ways reference the nodes by ids, i.e. no lng/lat or any other info. Similarly, relations just reference node, way and relation ids. 

What you need to do is maintain some sort of id -> node (or just lng/lat) map and then update the WayNodes with those values. That's not always easy depending on how much data you're trying to process. 

Also, incase you haven't seen it. https://download.geofabrik.de/ has pbf files for smaller regions that can be good for testing/dev.

**Comment by evanoberholster** [comment]
Thanks very much. I found the smaller regions. After playing around with the files I understand where I was wrong. Thank you again for the explanation.
