### ISSUE TITLE
How to write PBF or XML data?

### ISSUE THREAD

**Issue by Klaus-Tockloth** [paulmach/osm#9]
I want to duplicate some OSM nodes in my local environment. I'm able to find these nodes. Example:

```
node/42358880:6
map[string]string{
  "expected_rhn_route_relations":"3",
  "expected_rwn_route_relations":"3",
  "network:type":"node_network",
  "rhn_ref":"62",
  "rwn_ref":"21"
}
```
I want to write a similar node with a new ID into a PBF or XML file (for later merge). How to achieve this with this library?

**Comment by paulmach** [comment]
This library does not support writing of PBF files, but you can generate XML. Something like this, did actually test
```
o := osm.OSM{
	Nodes: osm.Nodes{
		{
			ID: 42358880, Version: 6,
			Visible: true,
			Tags: osm.Tags{
				{Key: "expected_rhn_route_relations", Value: "3"},
				{Key: "expected_rwn_route_relations", Value: "3"},
				{Key: "network:type", Value: "node_network"},
				{Key: "rhn_ref", Value: "62"},
				{Key: "rwn_ref", Value: "21"},
			},
		},
	},
}

data, _ := xml.Marshal(o)
fmt.Println(string(data))
```
This prints
```
<osm><node id="42358880" lat="0" lon="0" user="" uid="0" visible="true" version="6" changeset="0" timestamp="0001-01-01T00:00:00Z"><tag k="expected_rhn_route_relations" v="3"></tag><tag k="expected_rwn_route_relations" v="3"></tag><tag k="network:type" v="node_network"></tag><tag k="rhn_ref" v="62"></tag><tag k="rwn_ref" v="21"></tag></node></osm>
```

**Comment by Klaus-Tockloth** [comment]
Thanks for your answer. xml.Marshal() is exactly what I was looking for. Based on your library I have written a very special tool to preprocess OSM data. It is part of a processing chain to build maps for Android devices [freizeitkarte-osm.de](url). The tool itself can be found at [github.com/Klaus-Tockloth/osmpp](url).

PS: Thanks for writing and maintaining this library.
